theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right

site_name: BinaryJax
site_description: A JAX library for microlensing binary lens
site_author: Haibin Ren
site_url: https://coastego.github.io/BinaryJax

repo_url: https://github.com/CoastEgo/BinaryJax
repo_name: CoastEgo/BinaryJax

strict: false

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    
markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
        exclude:
            - "_overrides"
            - "_static/README.md"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                options:
                    show_source: false  # Don't include source code
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: false
                    show_signature_annotations: false
                    members_order: source
                    heading_level: 2
                # rendering:
                #     show_root_heading: true  # actually display anything at all...
                #     show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                #     show_if_no_docstring: true
                #     show_signature_annotations: true
                #     show_source: false  # don't include source code
                #     members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                #     heading_level: 1  # Makes everything top-level be <h4>. Child entries will be <h5> etc., but because of toc_depth, above, (deliberately) won't appear in the TOC.

nav:
    - 'index.md'
    - Basic API:
        - 'api/model.md'
        - 'api/solver.md'
        - 'api/util.md'
    - Real event modeling: 
        - KB-19-0371: 'example/KB0371.ipynb'